server:
  port: 4556

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#Application specific properties
api-error-messages:
  bad_request: Invalid Request
  created: Successfully created
  updated: Successfully updated
  accepted: Success
  internal_error: Unknown error occurred
api-required-header-keys:
  co-relationid: X-Correlation-Id
api-schema-file:
  submitanswer-schema: JsonSchema/submitAnswersSchema.json
api-version-number: 1

#Application specific unit test properties
unit-test:
  api-urls:
    submit_answer: /pcq/backend/submitAnswers

spring:
  application:
    name: PCQ Loader Service Functional Tests


pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

storage:
  account_name: ${STORAGE_ACCOUNT_NAME:pcqsharedaat}
  key: ${STORAGE_KEY:YV9rZXk=} #Base 64 encoded
  url: ${STORAGE_URL:http://0.0.0.0:10000}
  blob_lease_timeout: ${STORAGE_BLOB_LEASE_TIMEOUT:15}
  blob_copy_timeout_in_millis: ${BLOB_COPY_TIMEOUT_IN_MILLIS:30000}
  blob_copy_polling_delay_in_millis: ${BLOB_COPY_POLLING_DELAY_IN_MILLIS:500}
  blob_pcq_container: ${STORAGE_BLOB_PCQ_CONTAINER:pcq}
  blob_pcq_rejected-container: ${STORAGE_BLOB_PCQ_REJECTED-CONTAINER:pcq-rejected}
  blob_lease_acquire_delay_in_seconds: ${LEASE_ACQUIRE_DELAY_IN_SECONDS:30}

feign:
  allow:
    headers:
      - x-correlation-id

coRelationId: PCQ Loader Service
jwt_test_secret: ${JWT_SECRET:JwtSecretKey}
