server:
  port: 4556

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: PCQ Loader Service
  config:
    import: "optional:configtree:/mnt/secrets/pcq/"


smoke.test.enabled: false

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:"Test"}

pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

storage:
  account_name: ${STORAGE_ACCOUNT_NAME:devstoreaccount1}
  key: ${STORAGE_KEY:some_random_value;} #Base 64 encoded
  url: ${STORAGE_URL:http://0.0.0.0:10000/devstoreaccount1}
  blob_storage_download_path: ${STORAGE_DOWNLOAD_PATH:/var/tmp/pcq-loader/download/blobs}
  blob_lease_timeout: ${STORAGE_BLOB_LEASE_TIMEOUT:15}
  blob_copy_timeout_in_millis: ${BLOB_COPY_TIMEOUT_IN_MILLIS:30000}
  blob_copy_polling_delay_in_millis: ${BLOB_COPY_POLLING_DELAY_IN_MILLIS:500}
  blob_pcq_container: ${STORAGE_BLOB_PCQ_CONTAINER:pcq}
  blob_pcq_rejected-container: ${STORAGE_BLOB_PCQ_REJECTED-CONTAINER:pcq-rejected}
  blob_lease_acquire_delay_in_seconds: ${LEASE_ACQUIRE_DELAY_IN_SECONDS:30}
  processed_folder_name: processed

feign:
  allow:
    headers:
      - x-correlation-id

coRelationId: PCQ Loader Service
apiExecutionThreadDelay: 15000
security:
  jwt:
    secret: ${JWT_SECRET:a-very-long-and-boring-secret-key}
