server:
  port: 4556

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: PCQ Loader Service

smoke.test.enabled: false

application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:"Test"}

pcqBackendUrl: ${PCQ_BACKEND_URL:http://localhost:4550}

storage:
  account_name: ${STORAGE_ACCOUNT_NAME:pcqsharedaat}
  key: ${STORAGE_KEY:/vCzpx/TO+z1Y3sU5/7GHrWVDm6OEicPA59Hz4iMDD9fCWf6uPXbAug45+VCEkzEbvILtvD4pB9vumk/zXPgSQ==} #Base 64 encoded
  url: ${STORAGE_URL:https://pcqsharedaat.blob.core.windows.net/}
  blob_lease_timeout: ${STORAGE_BLOB_LEASE_TIMEOUT:15}
  blob_copy_timeout_in_millis: ${BLOB_COPY_TIMEOUT_IN_MILLIS:30000}
  blob_copy_polling_delay_in_millis: ${BLOB_COPY_POLLING_DELAY_IN_MILLIS:500}
  blob_pcq_container: ${STORAGE_BLOB_PCQ_CONTAINER:pcq}
  blob_lease_acquire_delay_in_seconds: ${LEASE_ACQUIRE_DELAY_IN_SECONDS:30}

feign:
  allow:
    headers:
      - x-correlation-id

coRelationId: PCQ Loader Service
